### ISSUE TITLE
first pass fs abstraction (support this.{in,out} in plugins)

### ISSUE THREAD

**Issue by hjdivad** [stefanpenner/fs-tree-diff#55]
### Docs

- [ ] update Readme
- [ ] inline YUI Docs

### Infect plugins with fs abstraction

- [x] broccoli-funnel (https://github.com/broccolijs/broccoli-funnel/tree/wip)
- [x] broccoli-merge-trees (https://github.com/broccolijs/broccoli-merge-trees/tree/wip)
- [x] broccoli-persistent-filter (https://github.com/stefanpenner/broccoli-persistent-filter/tree/fs-tree-facade)
- [x] broccoli-filter (https://github.com/broccolijs/broccoli-filter/tree/fs-tree-facade)
- [ ] ~~tree-sync~~

### infect more plugins with fs abstraction

Note that these don't currently use diffing so it's a bit more involved.

- [ ] broccoli-concat
- [ ] broccoli-plugin-kit

## finish projections

- see #54
  - [x] support cwd
  - [x] support include, exclude and files
  - [x] support setting parent (eg to let plugins make their out a projection of their in, cf funnel)

End result this should be able to almost entirely replace funnel; funnel would make its out a projection of its `in[0]`.

## handle unresolved questions

- [ ] think through implications of calling `start()` and clearing changes on a projection.  Currently this will clear the changes of the parent but we may need to be more precise here

##  Utilizing Change Tracking

- [ ] broccoli-funnel (#68)
- [ ] broccoli-merge-trees (#69)
- [ ] broccoli-persistent-filter (#67)
- [ ] broccoli-filter (#65)
- [ ] broccoli-plugin-kit
- [ ] ~~tree-sync~~

---

### infra

- [ ] _track should just track things in order and not update in place
- [ ] broccoli-plugin should path.resolve during reread()
- [ ] implement materialize (ensure disk matches entries; used when downstream does not support change tracking); flush all entries (symlinks) to disk, must be stable
- [ ] ensure fs errors match what happens by `fs` &c.  see #58
- [ ] implement `FSMergeTree` (`this.in` as a  merge of `this.in[0...]`)
- [ ] replace `linkedRoots` in funnel with projections (`this.out.cwd = x; this.out.include = y;` &c.)
- [ ] make broccoli-plugin set up `plugin.in`, `plugin.`out` (currently plugins hack this manually within `build` for testing)
  - [ ] handle 2 fs-facade aware plugins, in both directions (aware -> unaware and unaware -> aware)
  - handle 2 unaware plugins (ie what happens today; don't break stuff)
  - handle 1 aware and 1 unaware plugin (this will depend on materialize), again in both directions
- [ ] compare "legacy change tracking" to tree change tracking, in a debug mode.

- [ ] finally an integration test that ensures
  - things are working and
  - count of IOs goes down with this approach

### more infra

- [ ] fix windows path issues
- [ ] more error cases (#73)
- [ ] write YUI docs for the fs API
- [ ] write docs (readme/guides)

**Comment by stefanpenner** [comment]
going to experiment with contaminate broccoli-merge-trees to use the tree facade.

**Comment by hjdivad** [comment]
going to do projections so we can drop `linkRoots` in funnel (#54)

**Comment by stefanpenner** [comment]
broccoli-merge-trees WIP: https://github.com/broccolijs/broccoli-merge-trees/tree/wip

**Comment by stefanpenner** [comment]
This has been partially implemented by https://github.com/broccolijs/fs-merger + https://github.com/broccolijs/broccoli-output-wrapper which is in mainline broccoli now.
